[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solachess = "9ubJZxvjXxfhwZdVmUM4wzTQWCjLTvGDscyamSbk7XUa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
